name: Docker Image CI

on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "stable" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        docker buildx . --file Dockerfile --tag mayankgandhe/ts-scan
        docker push mayankgandhe/ts-scan
